# Generated by Django 5.2.17 on 2026-09-11 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0010_quizattempt_review_data_alter_quizattempt_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_index', models.PositiveIntegerField(default=0)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=0)),
                ('is_defeated', models.BooleanField(default=False)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('answered_question_ids', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'dungeon enemies',
                'ordering': ['enemy_index'],
            },
        ),
        migrations.CreateModel(
            name='DungeonRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('cleared', 'Cleared'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('current_hp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=0)),
                ('room_data', models.JSONField(blank=True, default=dict)),
                ('player_x', models.IntegerField(default=0)),
                ('player_y', models.IntegerField(default=0)),
                ('rules_key', models.CharField(default='free', max_length=20)),
                ('seed', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('xp_awarded', models.IntegerField(blank=True, default=None, null=True)),
                ('active_enemy', models.ForeignKey(blank=True, help_text='The battle in progress, so a page refresh resumes it instead of escaping it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dungeon.dungeonenemy')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_runs', to='courses.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DungeonInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_pieces', models.PositiveIntegerField(default=0)),
                ('skip_potions', models.PositiveIntegerField(default=0)),
                ('health_potions', models.PositiveIntegerField(default=0)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='dungeon.dungeonrun')),
            ],
            options={
                'verbose_name_plural': 'dungeon inventories',
            },
        ),
        migrations.AddField(
            model_name='dungeonenemy',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='dungeon.dungeonrun'),
        ),
        migrations.AddConstraint(
            model_name='dungeonrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'quiz'), name='unique_active_dungeon_run_per_quiz'),
        ),
        migrations.AddConstraint(
            model_name='dungeonenemy',
            constraint=models.UniqueConstraint(fields=('run', 'enemy_index'), name='unique_enemy_index_per_run'),
        ),
    ]
