# Generated by Django 5.2.17 on 2026-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonenemy',
            name='current_combo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
