# Generated by Django 5.2.17 on 2026-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0002_dungeonenemy_current_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonrun',
            name='review_mastered_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dungeonrun',
            name='review_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dungeonrun',
            name='run_type',
            field=models.CharField(choices=[('classic', 'Classic Expedition'), ('review', 'Review Run')], default='classic', max_length=20),
        ),
    ]
