# Generated by Django 5.2.17 on 2026-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0003_dungeonrun_review_mastered_question_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonenemy',
            name='armor_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dungeonenemy',
            name='name',
            field=models.CharField(default='Grunt', max_length=50),
        ),
        migrations.AddField(
            model_name='dungeonenemy',
            name='role',
            field=models.CharField(choices=[('grunt', 'Grunt'), ('guardian', 'Guardian')], default='grunt', max_length=20),
        ),
    ]
