# Generated by Django 6.1.1 on 2026-09-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_quizattempt_review_data_alter_quizattempt_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='best_streak_days',
            field=models.IntegerField(default=0),
        ),
    ]
