# Generated by Django 6.1.1 on 2026-09-10 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_userprofile_best_streak_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_opened_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_opened_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.course'),
        ),
    ]
