# Generated by Django 5.2.17 on 2026-09-26 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_userprofile_last_opened_chapter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual Selection'), ('external_assessment', 'External Assessment'), ('studyquest', 'StudyQuest Activity')], default='manual', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('subject_code', models.CharField(blank=True, max_length=64)),
                ('subject_name', models.CharField(max_length=255)),
                ('topic_names', models.JSONField(blank=True, default=list)),
                ('initial_score', models.FloatField(blank=True, help_text='Diagnostic assessment score percentage (e.g. 58.0)', null=True)),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('external_assessment_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_focuses', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_focuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'external_assessment'), models.Q(('external_assessment_id', ''), _negated=True)), fields=('user', 'external_assessment_id'), name='unique_user_external_assessment_id')],
            },
        ),
    ]
