# Generated by Django 6.1.1 on 2026-10-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_learningfocus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=140)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_links', to='courses.question')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='courses.coursetopic')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', through='courses.QuestionTopic', to='courses.coursetopic'),
        ),
        migrations.AddConstraint(
            model_name='coursetopic',
            constraint=models.UniqueConstraint(fields=('course', 'key'), name='unique_course_topic_key'),
        ),
        migrations.AddConstraint(
            model_name='questiontopic',
            constraint=models.UniqueConstraint(fields=('question', 'topic'), name='unique_question_topic'),
        ),
    ]
