# Generated by Django 5.2.17 on 2026-10-03 15:21
#
# Standard AddField/CreateModel operations.
#
# A note for existing development databases: an earlier, abandoned branch
# recorded its own ``0013``/``0014_course_generation_completed_at_and_more``,
# which created these same columns and the ``courses_coursegenerationjob``
# table. A database that ran that branch has the schema but not this migration.
#
# That is a stale-local-history problem, not a migration problem. Solve it with
# the documented command rather than by making this migration conditional:
#
#     python manage.py migrate courses 0016 --fake
#
# Fresh databases (including every test run and CI) apply this normally.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_startingknowledgecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='generation_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='generation_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='generation_stage',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.UUIDField(editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], db_index=True, default='queued', max_length=20)),
                ('stage', models.CharField(choices=[('queued', 'Queued'), ('reading_sources', 'Reading source materials'), ('preparing_content', 'Preparing the course structure'), ('generating_course', 'Generating lessons and assessments'), ('validating_course', 'Checking the generated content'), ('saving_course', 'Saving your course'), ('complete', 'Course ready'), ('failed', 'Generation failed')], default='queued', max_length=40)),
                ('source_bundle', models.JSONField(blank=True, default=dict)),
                ('generation_profile', models.JSONField(blank=True, default=dict)),
                ('custom_title', models.CharField(blank=True, default='', max_length=200)),
                ('study_focus', models.CharField(blank=True, default='', max_length=100)),
                ('plan_name', models.CharField(blank=True, default='free', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, default='', max_length=120)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('error_message', models.TextField(blank=True, default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='courses.course')),
            ],
            options={
                'ordering': ['queued_at'],
                'indexes': [models.Index(fields=['status', 'queued_at'], name='courses_cou_status_49630b_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'attempt_id'), name='unique_course_generation_attempt')],
            },
        ),
    ]
