# Generated by Django 6.1.1 on 2026-10-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_startingknowledgecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='startingknowledgecheck',
            name='graded_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
